// Métadonnées des apps (labels + icônes iOS/Android) — objet de données pur.
export const APP_META = {
  messages: {label:"Messages",   iosIcon:"💬", droidLabel:"Messages"},
  photos:   {label:"Photos",     iosIcon:"🖼️"},
  gallery:  {label:"Gallery",    iosIcon:"🖼️", droidLabel:"Gallery"},
  insta:    {label:"Instagram",  iosIcon:"📷"},
  music:    {label:"Music",    iosIcon:"🎵", droidLabel:"Music"},
  snapchat: {label:"Snapchat",   iosIcon:"👻"},
  grindr:   {label:"Grindr",     iosIcon:"🟡"},
  safari:   {label:"Safari",     iosIcon:"🧭"},
  browser:  {label:"Browser", iosIcon:"🌐", droidLabel:"Browser"},
  phone:    {label:"Phone",  iosIcon:"📞", droidLabel:"Phone"},
  notes:    {label:"Notes",      iosIcon:"📝", droidLabel:"Notes"},
  tumblr:   {label:"Tumblr",     iosIcon:"📓"},
  nikeplus: {label:"Nike+",      iosIcon:"👟"},
  bugsnap:    {label:"BugSnap",    iosIcon:"🪲",  droidLabel:"BugSnap"},
  youtube:    {label:"YouTube",    iosIcon:"▶️",  droidLabel:"YouTube"},
  maps:       {label:"Maps",       iosIcon:"🗺️",  droidLabel:"Maps"},
  calendar:   {label:"Calendar",     iosIcon:"📅",  droidLabel:"Calendar"},
  clock:      {label:"Clock",     iosIcon:"⏰",  droidLabel:"Clock"},
  calculator: {label:"Calcul.",    iosIcon:"🔢",  droidLabel:"Calcul."},
  contacts:   {label:"Contacts",   iosIcon:"👥",  droidLabel:"Contacts"},
  settings:   {label:"Settings",   iosIcon:"⚙️",  droidLabel:"Settings"},
  weather:    {label:"Weather",      iosIcon:"🌤️",  droidLabel:"Weather"},
  facebook:   {label:"Facebook",   iosIcon:"📘",  droidLabel:"Facebook"},
  gmail:      {label:"Mail",       iosIcon:"✉️",  droidLabel:"Gmail"},
  pinterest:  {label:"Pinterest",  iosIcon:"📌"},
  groupme:    {label:"GroupMe",    iosIcon:"💬"},
  starbucks:  {label:"Starbucks",  iosIcon:"☕"},
  soundcloud: {label:"SoundCloud", iosIcon:"🎧"},
  spotify:    {label:"Spotify",    iosIcon:"🎶"},
  espn:       {label:"ESPN",       iosIcon:"🏈"},
  mfp:        {label:"MyFitness",  iosIcon:"💪"},
  shazam:     {label:"Shazam",     iosIcon:"🎵"},
  wikipedia:  {label:"Wikipedia",  iosIcon:"📖",  droidLabel:"Wikipedia"},
  kindle:     {label:"Kindle",     iosIcon:"📚",  droidLabel:"Kindle"},
  reddit:     {label:"Reddit",     iosIcon:"👽",  droidLabel:"Reddit"},
  twitter:    {label:"Twitter",    iosIcon:"🐦",  droidLabel:"Twitter"},
  vpn:        {label:"VPN",        iosIcon:"🔐",  droidLabel:"VPN"},
  inaturalist:{label:"iNaturalist",iosIcon:"🔬",  droidLabel:"iNaturalist"},
  facetime: {label:"FaceTime",       iosIcon:"📹"},
  camera: {label:"Camera",  iosIcon:"📷", droidLabel:"Camera"},
  compass: {label:"Compass",        iosIcon:"🧭"},
  passbook: {label:"Passbook",        iosIcon:"🎫"},
  reminders: {label:"Reminders",         iosIcon:"✅"},
  messenger: {label:"Messenger",       iosIcon:"💬", droidLabel:"Messenger"},
  candycrush: {label:"Candy Crush",     iosIcon:"🍬", droidLabel:"Candy Crush"},
  templerun: {label:"Temple Run",      iosIcon:"🏃", droidLabel:"Temple Run"},
  angrybirds: {label:"Angry Birds",     iosIcon:"🐦", droidLabel:"Angry Birds"},
  subwaysurf: {label:"Subway Surfers",  iosIcon:"🛹", droidLabel:"Subway Surfers"},
  wordswfriends: {label:"Words w Friends", iosIcon:"📝", droidLabel:"Words w Friends"},

  files:      {label:"Fichiers",   iosIcon:"📁", droidLabel:"Fichiers"},
  polyvore: {label:"Polyvore",        iosIcon:"👗"},
  kik: {label:"Kik",             iosIcon:"💬"},
  runkeeper: {label:"RunKeeper",       iosIcon:"🏃"},
  hipstamatic: {label:"Hipstamatic",     iosIcon:"📷"},
  vivino: {label:"Vivino",          iosIcon:"🍷"},
  starwalk: {label:"Star Walk",       iosIcon:"⭐", droidLabel:"Star Walk"},
  wolframalpha: {label:"Wolfram Alpha",   iosIcon:"🧮", droidLabel:"Wolfram Alpha"},
  scannerradio: {label:"Scanner Radio",   iosIcon:"📡", droidLabel:"Scanner Radio"},
  findmyfriends: {label:"Find My Friends", iosIcon:"📍"},

  askfm:       {label:"Ask.fm",         iosIcon:"❓"},
  pou:         {label:"Pou",             iosIcon:"💩", droidLabel:"Pou"},
};
